import * as T from './three.module.js';
const canvas=document.querySelector('#studio-canvas'),host=document.querySelector('#studio-stage');const state=()=>window.portfolioState||{paused:false,room:'gallery'};let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false})}catch{document.querySelector('#studio-fallback').hidden=false;window.addEventListener('DOMContentLoaded',()=>window.enterPortfolio?.());throw Error('WebGL unavailable; standard portfolio remains usable')}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(42,1,.1,100);camera.position.set(8,6,11);const target=new T.Vector3(0,1.5,0),goal=new T.Vector3(8,6,11),lookGoal=new T.Vector3(0,1.5,0);scene.background=new T.Color('#e4d9d0');scene.fog=new T.Fog('#e4d9d0',22,50);const hemi=new T.HemisphereLight('#fff7ed','#8f7e8c',2.4);scene.add(hemi);const light=new T.DirectionalLight('#fff3e2',4);light.position.set(4,9,6);light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.camera.left=-12;light.shadow.camera.right=12;light.shadow.camera.top=12;light.shadow.camera.bottom=-12;light.shadow.normalBias=.04;scene.add(light);
const mat=c=>new T.MeshStandardMaterial({color:c,roughness:.65});const cream=mat('#e6d6c6'),wall=mat('#f3e9de'),gold=new T.MeshStandardMaterial({color:'#af926e',metalness:.65,roughness:.35}),wood=mat('#a98779'),plum=mat('#806678'),rose=mat('#cbb4b8');function mesh(g,m,x,y,z,parent=scene){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}function box(w,h,d,m,x,y,z,parent){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}
box(16,.25,12,cream,0,-.2,0);box(16,5,.18,wall,0,2.4,-5.9);box(.18,5,12,wall,-7.9,2.4,0);box(16,.12,.18,gold,0,.08,-5.73);box(.18,.12,12,gold,-7.72,.08,0);
// Architectural arches are real extruded 3D meshes, not a background image.
const archShape=new T.Shape();archShape.moveTo(-1.1,0);archShape.lineTo(-1.1,2.6);archShape.absarc(0,2.6,1.1,Math.PI,0,true);archShape.lineTo(1.1,0);archShape.lineTo(.9,0);archShape.lineTo(.9,2.6);archShape.absarc(0,2.6,.9,0,Math.PI,false);archShape.lineTo(-.9,0);archShape.closePath();for(const x of [-5,0,5])mesh(new T.ExtrudeGeometry(archShape,{depth:.16,bevelEnabled:false}),gold,x,.12,-5.68);
const textureLoader=new T.TextureLoader();function imageTexture(file){const tex=textureLoader.load('../assets/showcase/'+file);tex.colorSpace=T.SRGBColorSpace;return tex}const frames=[],frameGroup=new T.Group();scene.add(frameGroup);const files=['zy-invitations.webp','zy-cards.webp','zy-brands.webp','zy-books.webp','zy-covers.webp','zy-ads.webp'],ids=['invitations','cards','brands','books','covers','ads'];
for(let i=0;i<6;i++){const x=(i%3-1)*4.3,z=i<3?-4.7:.5,y=1.95;const panel=new T.Group();panel.position.set(x,y,z);box(2.35,2.8,.12,gold,0,0,0,panel);box(2.19,2.64,.12,wall,0,0,.07,panel);const art=mesh(new T.PlaneGeometry(1.95,2.4),new T.MeshBasicMaterial({map:imageTexture(files[i]),side:T.DoubleSide}),0,0,.14,panel);art.userData.collection=ids[i];frames.push(art);if(i>=3){box(.15,1.1,.15,gold,0,-1.95,0,panel);box(2.5,.15,1.2,cream,0,-2.45,0,panel);panel.rotation.y=-.15}frameGroup.add(panel)}
// Workspace, quiet seating area, and tactile gallery furniture.
const desk=new T.Group();desk.position.set(5,0,2.4);scene.add(desk);box(2.7,.18,1.4,wood,0,1.5,0,desk);for(const x of [-1.1,1.1])for(const z of [-.5,.5])box(.1,1.4,.1,gold,x,.7,z,desk);box(1.4,.85,.1,plum,0,2.1,-.3,desk);box(1.25,.7,.02,rose,0,2.1,-.235,desk);box(.1,.3,.1,gold,0,1.73,-.3,desk);box(.65,.04,.4,cream,0,1.63,.25,desk);mesh(new T.CylinderGeometry(.18,.16,.3,24),wall,-.9,1.72,.25,desk);const stool=mesh(new T.CylinderGeometry(.5,.5,.16,32),rose,5,.7,4.3);box(.08,.65,.08,gold,5,.33,4.3);const seating=new T.Group();seating.position.set(-5,0,2.5);scene.add(seating);box(2.4,.6,1.1,rose,0,.65,0,seating);box(2.4,1,.25,rose,0,1.1,-.45,seating);for(const x of [-1.1,1.1])box(.2,.7,1.2,plum,x,.95,0,seating);mesh(new T.CylinderGeometry(.7,.7,.15,40),cream,-4,1,4.3);mesh(new T.CylinderGeometry(.07,.07,.9,20),gold,-4,.5,4.3);
const sculpture=new T.Group();sculpture.position.set(0,1.25,3.6);scene.add(sculpture);mesh(new T.CylinderGeometry(.65,.75,.8,40),cream,0,-.75,0,sculpture);const knot=mesh(new T.TorusKnotGeometry(.38,.09,100,12),gold,0,.15,0,sculpture);for(const x of [-6.5,6.5]){mesh(new T.CylinderGeometry(.3,.23,.55,32),wood,x,.28,-4);for(let j=0;j<4;j++){const leaf=mesh(new T.SphereGeometry(.3,20,16),mat('#86947b'),x+Math.sin(j)*.2,1+j*.17,-4+Math.cos(j)*.2);leaf.scale.set(.6,1.7,.7)}}
const points=new Float32Array(150*3);for(let i=0;i<points.length;i+=3){points[i]=(Math.random()-.5)*16;points[i+1]=Math.random()*6;points[i+2]=(Math.random()-.5)*12}const particleGeometry=new T.BufferGeometry();particleGeometry.setAttribute('position',new T.BufferAttribute(points,3));const dust=new T.Points(particleGeometry,new T.PointsMaterial({color:'#c5a879',size:.025,transparent:true,opacity:.5}));scene.add(dust);
const ray=new T.Raycaster(),pointer=new T.Vector2(),discovered=new Set();let drag=null,dragged=false;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};dragged=false;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>4)dragged=true;goal.x=Math.max(-13,Math.min(13,goal.x+dx*.02));drag.x=e.clientX});canvas.addEventListener('pointerup',e=>{if(!dragged){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(frames)[0];if(hit)window.openCollection?.(hit.object.userData.collection)}drag=null});canvas.addEventListener('pointercancel',()=>drag=null);window.addEventListener('portfolio-discovery',e=>{discovered.add(e.detail);document.querySelector('#collected').textContent='Gallery discoveries '+discovered.size+' / 6'});
const rooms={gallery:{pos:[8,6,11],look:[0,1.5,-1],label:'THE GALLERY',caption:'A collection of considered details.'},desk:{pos:[8,3.5,6.7],look:[5,1.6,2],label:'THE WORKSPACE',caption:'Creative thinking. A practical approach.'},story:{pos:[-8,3.5,6.7],look:[-5,1.2,2],label:'MY STORY',caption:'Care, experience, and a little personality.'}};let tourTimer;function room(id){const r=rooms[id];state().room=id;goal.set(...r.pos);lookGoal.set(...r.look);document.querySelector('#room-label').textContent=r.label;document.querySelector('#room-caption').textContent=r.caption;document.querySelectorAll('[data-room]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.room===id));window.chime?.()}window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{clearInterval(tourTimer);document.querySelector('#tour').textContent='Guided visit';room(b.dataset.room)});document.querySelector('#tour').onclick=()=>{if(tourTimer){clearInterval(tourTimer);tourTimer=null;document.querySelector('#tour').textContent='Guided visit';return}let i=0;const order=['gallery','desk','story'];room(order[0]);document.querySelector('#tour').textContent='Stop visit';tourTimer=setInterval(()=>{i++;if(i>=3){clearInterval(tourTimer);tourTimer=null;document.querySelector('#tour').textContent='Guided visit';return}room(order[i])},4500)}});window.addEventListener('portfolio-motion',()=>{if(state().paused){clearInterval(tourTimer);tourTimer=null;document.querySelector('#tour').textContent='Guided visit'}});
function colors(){const dark=document.body.classList.contains('dark');const c=dark?'#463747':'#e4d9d0';scene.background.set(c);scene.fog.color.set(c);hemi.intensity=dark?1.5:2.4;light.intensity=dark?2.7:4}window.addEventListener('portfolio-theme',colors);window.addEventListener('DOMContentLoaded',colors);function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=w<600?58:42;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
// The supplied portrait is a depth-curved photo presentation, not a rigged human model.
const pc=document.querySelector('#portrait-canvas'),ps=new T.Scene(),cam=new T.PerspectiveCamera(35,1,.1,20);cam.position.z=4.5;const pr=new T.WebGLRenderer({canvas:pc,alpha:true,antialias:true});pr.setPixelRatio(Math.min(devicePixelRatio,1.5));const geo=new T.TorusKnotGeometry(.8,.23,100,20);const portrait=mesh(geo,gold,0,0,0,ps);ps.add(new T.HemisphereLight('#fff7ed','#806678',3));const emblemLight=new T.DirectionalLight('#fff7ed',3);emblemLight.position.set(2,3,4);ps.add(emblemLight);document.querySelector('#portrait-fallback').style.opacity=0;const portraitHost=document.querySelector('#portrait-stage');new ResizeObserver(()=>{pr.setSize(portraitHost.clientWidth,portraitHost.clientHeight,false);cam.aspect=portraitHost.clientWidth/portraitHost.clientHeight;cam.updateProjectionMatrix()}).observe(portraitHost);let portraitMouse={x:0,y:0};portraitHost.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;const r=portraitHost.getBoundingClientRect();portraitMouse={x:(e.clientX-r.left)/r.width-.5,y:(e.clientY-r.top)/r.height-.5}});portraitHost.addEventListener('pointerleave',()=>portraitMouse={x:0,y:0});
let t=0,previous=0;function animate(ts){const dt=Math.min((ts-previous)/1000,.04)||0;previous=ts;if(!state().paused){t+=dt;knot.rotation.y=t*.25;dust.rotation.y=t*.008;portrait.rotation.y+=(portraitMouse.x*.13-portrait.rotation.y)*.06;portrait.rotation.x+=(-portraitMouse.y*.07-portrait.rotation.x)*.06;portrait.position.y=Math.sin(t*.8)*.018}if(state().paused){camera.position.copy(goal);target.copy(lookGoal);portrait.rotation.set(0,0,0)}else{camera.position.lerp(goal,.045);target.lerp(lookGoal,.045)}camera.lookAt(target);renderer.render(scene,camera);pr.render(ps,cam);requestAnimationFrame(animate)}requestAnimationFrame(animate);T.DefaultLoadingManager.onLoad=()=>{document.querySelector('.loading-line i').style.width='100%';document.querySelector('#loading-copy').textContent='Your gallery is ready.';setTimeout(()=>window.enterPortfolio?.(),state().paused?0:500)};renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();document.querySelector('#studio-fallback').hidden=false});

